package com.apesdev.S.core.parameter;

/**
 * This file is generated by Parser's deployer. Please modify the root/config file and regenerate this file. * List of user parameters aiming to make a customizable deployment.
 */
public class Common {
     public static final String
            _URL_ROOT = "http://localhost:4200",
            _URL_BACKEND = "http://localhost:8080",
            DB_NAME = "CMSP4",
            DB_HOST = "mongodb://localhost"
           ;
}